export class LinkReferencia {

    selection = '';
    referencia = '';
    titulo = '';

    protected links: Map<string, string> = new Map([
        // agiles
        ['moscow', 'https://proagilist.es/blog/agilidad-y-gestion-agil/priorizar-requisitos-tecnica-priorizacion-moscow/'],
        ['scoring', 'https://comunidad.iebschool.com/metodologiasparaelcambio/2014/03/23/priorizando-historias-de-usuario/'],
        ['muda', 'https://prevencontrol.com/prevenblog/las-7-mudas/#:~:text=Los%20MUDA%2C%20t%C3%A9rmino%20japon%C3%A9s%20que,Sistema%20de%20producci%C3%B3n%20de%20Toyota'],
        ['5s', 'https://www.gestiopolis.com/5s-seiri-seiton-seiso-seiketsu-y-shitsuke-base-de-la-mejora-continua/'],
        ['muda#1', 'https://samuelcasanova.com/2014/03/los-7-desperdicios-del-desarrollo-de-software-i/'],
        ['muda#2', 'https://samuelcasanova.com/2014/03/los-7-desperdicios-del-desarrollo-de-software-y-ii/'],
        ['planningPoker', 'https://samuelcasanova.com/2016/01/estimacion-agil-con-la-tecnica-planning-poker/'],
        // analisis
        ['comportamiento', 'https://es.wikipedia.org/wiki/Modelo_de_comportamiento_(inform%C3%A1tica)'],
        ['dominio', 'https://www.redalyc.org/jatsRepo/4768/476862530003/html/index.html#:~:text=El%20An%C3%A1lisis%20de%20Dominio%20es,la%20identificaci%C3%B3n%2C%20el%20an%C3%A1lisis%20y'],
        ['case', 'https://www.tutorialspoint.com/es/software_engineering/case_tools_overview.htm'],
        ['divide', 'https://es.khanacademy.org/computing/computer-science/algorithms/merge-sort/a/divide-and-conquer-algorithms'],
        ['diseño', 'https://www.bravent.net/la-importancia-de-un-buen-diseno-del-software/'],
        ['crc', 'https://medium.com/@marcosrrg9813/tarjetas-crc-clase-responsabilidad-colaborador-81924cec3af0'],
        // arquitecturas
        ['definicion', 'https://cgrw01.cgr.go.cr/rup/RUP.es/SmallProjects/core.base_rup/guidances/concepts/software_architecture_4269A354.html'],
        ['capas', 'https://geeks.ms/jkpelaez/2009/05/30/arquitectura-basada-en-capas/'],
        ['cliente', 'https://desarrolloweb.com/articulos/arquitectura-cliente-servidor.html'],
        ['intermediario', 'https://conasa.grupocibernos.com/blog/patrones-comunes-de-arquitecturas-de-software'],
        ['servicios', 'https://aws.amazon.com/es/microservices/'],
        ['hexagonal', 'https://medium.com/@edusalguero/arquitectura-hexagonal-59834bb44b7f'],
        ['otrasArquitecturas', 'https://medium.com/@maniakhitoccori/los-10-patrones-comunes-de-arquitectura-de-software-d8b9047edf0b'],
        // buenas practicas
        ['practicas1', 'https://www.tithink.com/es/2018/06/13/12-buenas-practicas-para-el-desarrollo-software/'],
        ['practicas2', 'https://sg.com.mx/revista/mejores-pr%C3%A1cticas-para-el-desarrollo-software'],
        ['practicas3', 'https://velneo.es/15-buenas-practicas-proyectos-desarrollo-software/'],
        ['practicas4', 'http://www.noussintelligence.com/desarrollo-software-buenas-practicas-recomendaciones/'],
        ['demeter', 'https://www.adictosaltrabajo.com/2015/07/24/ley-de-demeter/'],
        ['complejidad', 'http://oscarmoreno.com/la-complejidad-ciclomatica/'],
        ['logging', 'https://itnext.io/logger-or-debugger-which-one-to-choose-3f6a72200b15'],
        // calidad
        ['metricas', 'https://searchdatacenter.techtarget.com/es/consejo/23-metricas-de-desarrollo-de-software-que-monitorear-hoy'],
        ['metricasEnCodigo', 'https://blog.desafiolatam.com/metricas-de-calidad-de-software/#:~:text=M%C3%A9tricas%20de%20calidad%20de%20software%20es%20un%20conjunto%20de%20medidas,comparar%20o%20planificar%20estas%20aplicaciones.&text=Tambi%C3%A9n%2C%20es%20necesario%20definir%20las,los%20resultados%20de%20estas%20m%C3%A9tricas'],
        ['cleanCode', 'https://medium.com/@tijuhasz/in-one-of-the-most-groundbreaking-practical-books-on-software-development-clean-code-right-in-3ef3006c68f2'],
        // compilación
        ['compilacion', 'https://developer.mozilla.org/es/docs/Glossary/Compile'],
        ['nivel', 'https://desarrolloweb.com/articulos/2358.php#:~:text=Existen%20dos%20tipos%20de%20lenguajes,y%20los%20de%20alto%20nivel.&text=Los%20lenguajes%20m%C3%A1s%20pr%C3%B3ximos%20a,denominan%20lenguajes%20de%20alto%20nivel.'],
        ['interprete', 'https://yosoy.dev/diferencia-entre-lenguajes-compilados-e-interpretados/'],
        ['transpilacion', 'https://ingenieriadesoftware.es/diferencia-transpilacion-compilacion/#:~:text=Si%20traduce%20c%C3%B3digo%20entre%20lenguajes,a%20Bytecode%20ser%C3%ADa%20una%20compilaci%C3%B3n.'],
        // conocimentos empiricos
        ['balas', 'https://gist.github.com/esparta/582e43af7b803e0aaf69'],
        ['lehman', 'https://medium.com/@cartontabla/las-leyes-de-lehman-b57c623c3404#:~:text=Las%20Leyes%20de%20Lehman%20son,digamos%20que%20podr%C3%ADan%20ser%20ampliadas)'],
        ['conway', 'https://www.javiergarzas.com/2015/06/conway.html'],
        ['murphy', 'https://www.caracteristicas.co/ley-de-murphy/'],
        ['cristales', 'https://lamenteesmaravillosa.com/la-teoria-las-ventanas-rotas/'],
        ['quo', 'https://psicologiaymente.com/social/sesgo-statu-quo#:~:text=El%20sesgo%20del%20statu%20quo%20es%20un%20sesgo%20de%20tipo,sobre%20un%20aspecto%20en%20concreto.'],
        ['costo', 'https://psicologiaymente.com/psicologia/falacia-costo-hundido#:~:text=En%20resumen%2C%20la%20falacia%20del,cuyas%20expectativas%20son%20muy%20desalentadoras.'],
        ['tiposProgramadores', 'https://stevenbenner.com/2010/07/the-5-types-of-programmers/'],
        ['sesgos', 'https://www.brainvestigations.com/neurociencia/sesgo-cognitivo-negocios/'],
        ['multitarea', 'https://www.sodexo.es/blog/multitarea-multitasking/'],
        ['maxwellCurve', 'https://blog.axosoft.com/the-maxwell-curve-blunder-in-the-name-of-scrum/'],
        ['pendulo', 'http://www.grupocrece.es/blog/Psicolog%C3%ADala-ley-del-pndulo-en-psicologa'],
        // docker
        ['docker', 'https://www.xataka.com/otros/docker-a-kubernetes-entendiendo-que-contenedores-que-mayores-revoluciones-industria-desarrollo'],
        ['images', 'https://clouding.io/hc/es/articles/360010283060-Trabajando-con-im%C3%A1genes-en-Docker'],
        ['containers', 'https://aulasoftwarelibre.github.io/taller-de-docker/containers/'],
        ['volumes', 'https://www.josedomingo.org/pledin/2016/05/gestion-del-almacenamiento-en-docker/#:~:text=Un%20volumen%20es%20un%20directorio,podemos%20montar%20un%20mismo%20volumen.'],
        ['network', 'https://dockertips.com/algo_sobre_redes'],
        ['file', 'https://docs.docker.com/develop/develop-images/dockerfile_best-practices/'],
        ['compose', 'https://dockertips.com/utilizando-docker-compose#:~:text=Docker%20Compose%20es%20una%20herramienta%20que%20permite%20simplificar%20el%20uso%20de%20Docker.&text=En%20vez%20de%20utilizar%20Docker,Engine%20a%20realizar%20tareas%2C%20programaticamente'],
        // estrategias de desarrollo
        ['ddd', 'https://github.com/jatubio/5minutos_laravel/wiki/Resumen-sobre-DDD.-Domain-Driven-Design'],
        ['bdd', 'https://www.itdo.com/blog/que-es-bdd-behavior-driven-development/#:~:text=Given%2DWhen%2DThen%20como%20lenguaje%20com%C3%BAn%20con%20BDD,que%20se%20van%20a%20ejecutar'],
        ['tdd', 'https://www.paradigmadigital.com/dev/tdd-como-metodologia-de-diseno-de-software/'],
        ['atdd', 'https://www.javiergarzas.com/2015/07/que-es-eso-de-atdd.html'],
        ['analisis', 'https://www.ubjonline.mx/en-que-consisten-los-analisis-top-down-y-bottom-up/'],
        ['tld', 'https://medium.com/swlh/tdd-vs-tld-and-what-is-the-minimum-code-coverage-needed-f380181d3400'],
        // frameworks
        ['frameworks', 'https://neoattack.com/neowiki/framework/'],
        ['ioc', 'https://medium.com/all-you-need-is-clean-code/inversi%C3%B3n-de-control-principio-de-hollywood-dont-call-us-we-ll-call-you-179e9c70e3d0'],
        ['iod', 'https://www.arquitecturajava.com/el-patron-de-inyeccion-de-dependencia/'],
        ['spring', 'https://spring.io/'],
        ['angular', 'https://platzi.com/desarrollo-angular/?utm_source=google&utm_medium=cpc&utm_campaign=9328433462&utm_adgroup=94733526952&utm_content=452203650165&&gclid=Cj0KCQiA3smABhCjARIsAKtrg6LJDf4V2JKL7esXLHrcbpL4NIx8o-pixGZe0YdtUIU5HflNhR74Md0aArb4EALw_wcB&gclsrc=aw.ds'],
        // git
        ['introduccion', 'https://git-scm.com/book/es/v2/Inicio---Sobre-el-Control-de-Versiones-Acerca-del-Control-de-Versiones'],
        ['repositorios', 'https://git-scm.com/book/es/v2/Fundamentos-de-Git-Trabajar-con-Remotos'],
        ['ramas', 'https://git-scm.com/book/es/v2/Ramificaciones-en-Git-Procedimientos-B%C3%A1sicos-para-Ramificar-y-Fusionar'],
        ['protocolos', 'https://git-scm.com/book/es/v2/Git-en-el-Servidor-Los-Protocolos'],
        ['versiones', 'https://git-scm.com/book/es/v2/Git-en-entornos-distribuidos-Manteniendo-un-proyecto'],
        ['forks', 'https://git-scm.com/book/es/v2/GitHub-Participando-en-Proyectos'],
        ['stash', 'https://git-scm.com/book/es/v2/Herramientas-de-Git-Guardado-r%C3%A1pido-y-Limpieza'],
        ['merge', 'https://git-scm.com/book/es/v2/Herramientas-de-Git-Fusi%C3%B3n-Avanzada'],
        ['atributos', 'https://git-scm.com/book/es/v2/Personalizaci%C3%B3n-de-Git-Git-Attributes'],
        ['migracion', 'https://git-scm.com/book/es/v2/Git-y-Otros-Sistemas-Migraci%C3%B3n-a-Git'],
        ['flow', 'https://aprendegit.com/que-es-git-flow/'],
        ['remotos', 'https://www.clubdetecnologia.net/blog/2017/github-vs-gitlab-vs-bitbucket-que-repositorio-elegir/'],
        ['practicas', 'https://codigofacilito.com/articles/41'],
        // historias de usuario
        ['historias', 'https://apiumhub.com/es/tech-blog-barcelona/como-escribir-buenas-historias-de-usuario/'],
        ['objetivos', 'https://apiumhub.com/es/tech-blog-barcelona/como-escribir-buenas-historias-de-usuario/'],
        ['partes', 'https://apiumhub.com/es/tech-blog-barcelona/como-escribir-buenas-historias-de-usuario/'],
        ['invest', 'https://apiumhub.com/es/tech-blog-barcelona/como-escribir-buenas-historias-de-usuario/'],
        ['smart', 'https://beagilemyfriend.com/historias-de-usuario-invest-smart/'],
        ['3c', 'https://julibetancur.blog/tag/tres-c/'],
        ['gherkin', 'https://blog.thiga.co/es/gherkin/'],
        ['agil', 'https://agilemanifesto.org/iso/es/manifesto.html'],
        ['descomposicionHU', 'https://www.javiergarzas.com/2012/05/descomponer-historias-de-usuario-en-tareas-1.html'],
        // malas practicas
        ['callbackhell', 'https://codearmy.co/que-es-el-callback-hell-y-como-evitarlo-4af418a6ed14'],
        ['cosas1', 'https://softgrade.mx/5-causas-afectan-la-calidad-software/'],
        ['cosas2', 'https://blog.gft.com/es/2016/01/20/las-10-malas-practicas-mas-comunes-en-la-gestion-de-proyectos/'],
        ['cosas3', 'https://blog.gft.com/es/2016/01/20/las-10-malas-practicas-mas-comunes-en-la-gestion-de-proyectos/'],
        // meta-caracteristicas
        ['metaDatos', 'https://blog.powerdata.es/el-valor-de-la-gestion-de-datos/que-son-los-metadatos-y-cual-es-su-utilidad'],
        ['metaClase', 'https://quesignificado.org/que-es-una-metaclase/'],
        ['reflexion', 'https://es.linkfang.org/wiki/Reflexi%C3%B3n_(inform%C3%A1tica)'],
        ['asserts', 'https://www.adictosaltrabajo.com/2016/01/07/haz-tu-codigo-mas-fiable-con-asserts/'],
        ['excepciones', 'https://universidad-de-los-andes.gitbooks.io/fundamentos-de-programacion/content/Nivel4/5_ManejoDeLasExcepciones.html'],
        ['scafolding', 'https://medium.com/@srinathsrs104/scaffolding-54ac4e47e133'],
        ['cache', 'https://medium.com/bancolombia-tech/dise%C3%B1ando-una-estrategia-de-cach%C3%A9-39366876009b'],
        // metodologias
        ['agiles', 'https://www.iebschool.com/blog/que-son-metodologias-agiles-agile-scrum/'],
        ['scrum', 'https://www.iebschool.com/blog/metodologia-scrum-agile-scrum/'],
        ['kanban', 'https://www.iebschool.com/blog/metodologia-kanban-agile-scrum/'],
        ['elevator', 'https://www.iebschool.com/blog/las-claves-para-realizar-un-elevator-pitch-lean-startup/'],
        ['canvas', 'https://www.iebschool.com/blog/que-es-el-modelo-canvas-y-como-aplicarlo-a-tu-negocio-agile-scrum/'],
        ['tradicionales', 'https://www.tutorialspoint.com/es/software_engineering/software_development_life_cycle.htm'],
        ['cascada', 'https://www.ionos.es/digitalguide/paginas-web/desarrollo-web/el-modelo-en-cascada/'],
        ['espiral', 'https://www.ionos.es/startupguide/productividad/modelo-en-espiral/'],
        ['iterativo', 'https://proyectosagiles.org/desarrollo-iterativo-incremental/'],
        ['extrema', 'https://www.diegocalvo.es/metodologia-xp-programacion-extrema-metodologia-agil/'],
        ['v', 'https://ingsoftware.weebly.com/ciclo-de-vida-en-v.html'],
        ['rup', 'https://metodoss.com/metodologia-rup/'],
        ['kaizen', 'https://www.movertis.com/blog/que-es-la-metodologia-kaizen/#:~:text=En%20japon%C3%A9s%2C%20las%20palabras%20Kai,se%20deja%20nunca%20de%20ejecutar'],
        // nube
        ['nube', 'https://azure.microsoft.com/es-es/overview/what-are-private-public-hybrid-clouds/'],
        ['iaas-paas-saas', 'https://www.ambit-bst.com/blog/definici%C3%B3n-de-iaas-paas-y-saas-en-qu%C3%A9-se-diferencian'],
        ['api', 'https://www.ticbeat.com/tecnologias/que-es-una-api-para-que-sirve/'],
        ['rest', 'https://www.oscarblancarteblog.com/2017/03/06/soap-vs-rest-2/'],
        ['restfull', 'http://adwe.es/general/colaboraciones/servicios-web-restful-con-http-parte-i-introduccion-y-bases-teoricas/'],
        ['caracteristicas', 'https://adwe.es/codigo/apis-codigo/servicios-web-restful-con-http-parte-ii-ejemplos/'],
        ['madurezDeUnaApi', 'https://restfulapi.net/richardson-maturity-model/'],
        // otros
        ['escalamiento', 'https://www.oscarblancarteblog.com/2017/03/07/escalabilidad-horizontal-y-vertical/'],
        ['scraping', 'https://www.ionos.es/digitalguide/paginas-web/desarrollo-web/que-es-el-web-scraping/'],
        ['cdci', 'https://www.aplyca.com/es/blog/integracion-entrega-continua-ci-cd'],
        ['devops', 'https://www.paradigmadigital.com/techbiz/que-es-devops-y-sobre-todo-que-no-es-devops/#:~:text=Como%20conclusi%C3%B3n%2C%20qued%C3%A9monos%20con%20una,s%C3%B3lo%20en%20desarrollar%20y%20puedan'],
        ['scope', 'https://platzi.com/blog/como-funciona-el-scope-en-javascript/'],
        ['precedencia', 'https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Operators/Operator_Precedence'],
        ['mvp', 'https://www.inboundcycle.com/blog-de-inbound-marketing/bid/189238/qu-es-el-mvp-o-producto-m-nimo-viable'],
        ['artesanos', 'https://manifesto.softwarecraftsmanship.org/#/es'],
        ['verticalAndHorizontal', 'https://xurxodev.com/vertical-scile/'],
        // paradigmas
        ['imperativo', 'https://www.ionos.es/digitalguide/paginas-web/desarrollo-web/paradigmas-de-programacion/'],
        ['funcional', 'https://codigofacilito.com/articulos/programacion-funcional'],
        ['scripting', 'https://www.ionos.es/digitalguide/paginas-web/desarrollo-web/que-son-los-lenguajes-de-scripting/'],
        ['reactiva', 'https://profile.es/blog/que-es-la-programacion-reactiva-una-introduccion/'],
        ['marcado', 'https://blog.educacionit.com/2018/12/26/diferencia-entre-lenguajes-de-scripting-lenguajes-de-marcado-y-lenguajes-de-programacion/'],
        ['aspectos', 'https://www.baeldung.com/spring-aop'],
        // patrones
        ['definicionPatrones', 'http://www.ecured.cu/Patrones_de_dise%C3%B1o_y_arquitectura'],
        ['gof', 'http://www.cleformacion.com/tic-tek/-/blogs/patrones-gof'],
        ['desglosegof', 'https://refactoring.guru/es/design-patterns/catalog'],
        ['grasp', 'https://www.adictosaltrabajo.com/2003/12/22/grasp/'],
        ['desglosegrasp', 'https://juan-garcia-carmona.blogspot.com/search/label/patr%C3%B3n'],
        ['dao', 'https://www.genbeta.com/desarrollo/patrones-de-diseno-active-record-vs-dao'],
        ['antipatrones', 'https://sg.com.mx/revista/11/anti-patrones-la-mejor-forma-hacer-un-pesimo-sistema-software'],
        // personas
        ['personasYprocesos', 'https://www.heflo.com/es/blog/bpm/personas-procesos-tecnologia/'],
        ['gestionDeServicios', 'https://www.ambit-bst.com/blog/itsm.-todo-lo-que-debes-saber-sobre-la-gesti%C3%B3n-de-servicios-it'],
        ['gestionDeActivos', 'https://freshservice.com/latam/it-asset-management-software/'],
        ['fidelizacion', 'https://elviajedelcliente.com/fidelizacion-de-clientes/'],
        // poo
        ['poo', 'https://desarrolloweb.com/articulos/499.php'],
        ['pooPilares', 'https://www.campusmvp.es/recursos/post/los-conceptos-fundamentales-sobre-programacion-orientada-objetos-explicados-de-manera-simple.aspx'],
        ['composicion', 'https://www.seas.es/blog/informatica/agregacion-vs-composicion-en-diagramas-de-clases-uml/'],
        ['pooStatic', 'https://desarrolloweb.com/articulos/metodos-atributos-static-poo.html'],
        ['sobrecarga', 'https://www.netmentor.es/Entrada/sobrecarga-metodos'],
        ['acoplamiento', 'https://jummp.wordpress.com/2010/06/26/acoplamiento-aferente-acoplamiento-eferente-inestabilidad-y-abstraccion-i/'],
        ['contratos', 'https://dosideas.com/wiki/Dise%C3%B1o_Por_Contrato'],
        ['descomposicion', 'http://miguedt.blogspot.com/2013/01/descomposicion-funcional.html#:~:text=La%20descomposici%C3%B3n%20funcional%20se%20refiere,en%20funci%C3%B3n%20de%20la%20composici%C3%B3n'],
        ['herencia', 'https://www.ecured.cu/Herencia_(Inform%C3%A1tica)'],
        ['polimorfismo', 'https://devexperto.com/herencia-vs-composicion/'],
        ['herVScomp', 'https://devexperto.com/herencia-vs-composicion/'],
        ['enlaces', 'https://es.fondoperlaterra.org/comdifference-between-static-and-dynamic-binding-2'],
        // pruebas
        ['principios', 'https://todosqa.com/siete-principios-del-proceso-de-prueba/'],
        ['manifiesto', 'https://www.adictosaltrabajo.com/2019/12/18/testing-en-un-mundo-agile/'],
        ['tiposPruebas', 'https://visual-engin.com/2017/10/26/importancia-pruebas-de-software-testing/'],
        ['beneficios', 'https://platzi.com/blog/testing-ventajas-formas-de-realizar-pruebas/'],
        ['nombramiento', 'https://www.petrikainulainen.net/programming/testing/writing-clean-tests-naming-matters/'],
        ['first', 'https://www.paradigmadigital.com/dev/principio-first-aumentar-la-calidad-tests-unitarios/'],
        ['sutydoc', 'https://www.javiergarzas.com/2015/09/que-estoy-probando-y-cuales-son-mis-dependencias-en-testing.html'],
        ['dobles', 'https://www.codurance.com/publications/2019/04/08/introduction-to-test-doubles'],
        ['aaa', 'http://oscarmoreno.com/pruebas-unitarias/'],
        ['gwt', 'https://softwareengineering.stackexchange.com/questions/308160/differences-between-given-when-then-gwt-and-arrange-act-assert-aaa'],
        ['piramide', 'https://medium.com/@wc.testing.qa/la-famosa-pir%C3%A1mide-de-cohn-y-la-dura-realidad-e1250dfbe5f3'],
        ['triangulo', 'https://proyectosagiles.org/triangulo-hierro/'],
        ['cobertura', 'https://argonur.com/2020/05/11/code-coverage-cobertura-de-codigo/'],
        ['falsos', 'https://www.qalovers.com/2015/03/diferencia-entre-falso-positivo-y-falso_5.html#:~:text=La%20definici%C3%B3n%20de%20falso%20negativo,sistema%20que%20est%C3%A1%20realmente%20infectada.%22&text=Un%20falso%20negativo%20llevado%20a,cuando%20en%20realidad%20est%C3%A1%20fallando.'],
        ['QAperson', 'https://www.bbvaapimarket.com/es/mundo-api/que-es-qa-y-por-que-no-debe-faltar-en-tu-proyecto/'],
        // refactorización
        ['codigolimpio', 'https://refactoring.guru/es/refactoring/what-is-refactoring'],
        ['deudatecnica', 'https://refactoring.guru/es/refactoring/technical-debt'],
        ['tiposDeudaTecnica', 'https://www.ionos.es/digitalguide/paginas-web/desarrollo-web/deuda-tecnica-explicada/'],
        ['comentarios', 'https://www.scrummanager.net/bok/index.php?title=Deuda_t%C3%A9cnica'],
        ['cuandorefactorizar', 'https://refactoring.guru/es/refactoring/when'],
        ['comorefactorizar', 'https://refactoring.guru/es/refactoring/how-to'],
        // requisitos
        ['funcionales', 'https://medium.com/@requeridosblog/requerimientos-funcionales-y-no-funcionales-ejemplos-y-tips-aa31cb59b22a'],
        ['NOfuncionales', 'https://medium.com/@requeridosblog/requerimientos-funcionales-y-no-funcionales-ejemplos-y-tips-aa31cb59b22a'],
        ['negocio', 'https://requeridos.com/que-es-el-valor-de-negocio-y-como-medirlo/'],
        ['ambiguedad', 'https://requeridos.com/requerimientos-menos-es-mas/'],
        ['calidad', 'https://platzi.com/tutoriales/1248-pro-arquitectura/5498-atributos-de-calidad-de-un-producto-de-software/'],
        ['tradeoff', 'https://medium.com/analysts-corner/those-other-requirements-quality-attributes-and-their-inescapable-tradeoffs-31dc0691974d'],
        // principios
        ['solid', 'https://profile.es/blog/principios-solid-desarrollo-software-calidad/'],
        ['kiss', 'https://manuelzapata.co/principio-kiss-keep-it-simple-stupid/'],
        ['yagni', 'https://www.genbeta.com/desarrollo/la-navaja-de-occam-kiss-y-yagni-la-simplicidad-en-el-codigo-no-deberia-ser-solo-postureo-developer'],
        ['occam', 'https://www.genbeta.com/desarrollo/la-navaja-de-occam-kiss-y-yagni-la-simplicidad-en-el-codigo-no-deberia-ser-solo-postureo-developer'],
        ['dry', 'https://tantacom.com/principios-diseno-software-kiss-dry-solid/'],
        ['hollywood', 'https://www.genbeta.com/desarrollo/doce-principios-de-diseno-que-todo-desarrollador-deberia-conocer'],
        ['tellDontAsk', 'https://www.disrupciontecnologica.com/tell-dont-ask/?reload=977836'],
        // seguridad
        ['firewall', 'https://idgrup.com/firewall-que-es-y-como-funciona/#:~:text=Un%20firewall%2C%20tambi%C3%A9n%20llamado%20cortafuegos,ordenadores%20de%20una%20misma%20red'],
        ['protocolos', 'https://www.websecurity.digicert.com/es/es/security-topics/what-is-ssl-tls-https'],
        ['proxy', 'https://www.welivesecurity.com/la-es/2020/01/02/que-es-proxy-para-que-sirve/'],
        ['estatico', 'https://www.welivesecurity.com/la-es/2021/01/18/analisis-estatico-codigo-fuente-orientado-a-seguridad/'],
        ['ciberSeguridad', 'https://latam.kaspersky.com/resource-center/definitions/what-is-cyber-security'],
        ['cia', 'https://searchdatacenter.techtarget.com/es/opinion/Que-es-la-triada-de-la-CIA'],
        ['noRepudio', 'https://www.unir.net/ingenieria/revista/no-repudio-seguridad-informatica/'],
        ['matrizDeRiesgo', 'https://www.protek.com.py/novedades/objetivos-de-una-matriz-de-riesgos/'],
        ['condicionDeCarrera', 'https://ciberseguridad.com/amenzas/vulnerabilidades/condicion-de-carrera/'],
        // smells codes
        ['codesmells', 'https://openwebinars.net/blog/code-smells-y-deuda-tecnica/'],
        ['tiposSmellCodes', 'https://refactoring.guru/es/refactoring/smells'],
        ['desglose', 'https://refactoring.guru/es/refactoring/smells'],
        ['casos', 'https://refactoring.guru/es/refactoring/smells'],
        ['payoff', 'https://refactoring.guru/es/refactoring/smells'],
        // sql & No sql
        ['sql', 'https://www.w3schools.com/sql/default.asp'],
        ['dbms', 'https://www.astera.com/es/type/blog/database-management-software/'],
        ['crud', 'https://www.ionos.es/digitalguide/paginas-web/desarrollo-web/crud-las-principales-operaciones-de-bases-de-datos/'],
        ['dl', 'https://platzi.com/blog/que-es-ddl-dml-dcl-y-tcl-integridad-referencial/'],
        ['integridad', 'https://platzi.com/blog/que-es-ddl-dml-dcl-y-tcl-integridad-referencial/'],
        ['erd', 'https://www.lucidchart.com/pages/es/que-es-un-diagrama-entidad-relacion'],
        ['normalizacion', 'https://docs.microsoft.com/en-us/office/troubleshoot/access/database-normalization-description'],
        ['nosql', 'https://pandorafms.com/blog/es/bases-de-datos-nosql/'],
        ['tiposBD', 'https://www.acens.com/wp-content/images/2014/02/bbdd-nosql-wp-acens.pdf'],
        ['acid', 'https://dosideas.com/noticias/base-de-datos/973-acid-en-las-bases-de-datos'],
        ['orm', 'https://programarfacil.com/blog/que-es-un-orm/'],
        ['consistenciaEventual', 'https://medium.com/@gabanox/consistencia-eventual-en-s3-6ba5b2ecd721'],
        // uml
        ['uml', 'https://diagramasuml.com/'],
        ['clase', 'https://diagramasuml.com/diagrama-de-clases/'],
        ['componentes', 'https://diagramasuml.com/componentes/'],
        ['despliegue', 'https://diagramasuml.com/despliegue/'],
        ['usos', 'https://diagramasuml.com/casos-de-uso/'],
        ['secuencia', 'https://diagramasuml.com/secuencia/'],
        ['actividades', 'https://diagramasuml.com/actividades/'],
        ['paquetes', 'https://diagramasuml.com/paquetes/'],
        ['estados', 'https://diagramasuml.com/estados/'],
        ['vista', 'https://es.wikipedia.org/wiki/Modelo_de_Vistas_de_Arquitectura_4%2B1'],
        // versionamiento
        ['git', 'https://david-estevez.gitbooks.io/the-git-the-bad-and-the-ugly/content/es/control-de-versiones.html'],
        ['dependencias', 'https://www.hongkiat.com/blog/manage-dependencies-tools-webdev/'],
        ['gradlevsmaven', 'https://www.chakray.com/es/gradle-vs-maven-definiciones-diferencias/'],
        ['versiones', 'https://ed.team/blog/como-se-deciden-las-versiones-del-software'],
        // web
        ['spa', 'https://desarrolloweb.com/articulos/que-es-una-spa.html#:~:text=En%20pocas%20palabras%2C%20SPA%20son,html'],
        ['pwa', 'https://www.iebschool.com/blog/progressive-web-apps-analitica-usabilidad/'],
        ['seo', 'https://www.40defiebre.com/guia-seo/que-es-seo-por-que-necesito'],
        ['espacio', 'https://www.dsigno.es/blog/diseno-grafico/espacios-negativos-en-diseno-grafico'],
        ['diseno', 'https://seocom.agency/es/blog/diseno-grafico-web/']
    ]);

    public tittles: Map<string, string> = new Map([
        // agiles
        ['moscow', 'MOSCOW'],
        ['scoring', 'Theme Scoring'],
        ['muda', 'Desperdicio'],
        ['5s', 'Seiri, Seiton, Seiso, Seiketsu, Shitsuke'],
        ['muda#1', 'Muda en el software, paralelismos 1-3'],
        ['muda#2', 'Muda en el software, paralelismos 4-7'],
        ['planningPoker', 'Planning Poker y la estimación agil'],
        // analisis
        ['comportamiento', 'Comportamiento del sistema'],
        ['dominio', 'Analisis de Dominio'],
        ['case', 'Herramientas Case'],
        ['divide', 'Divide y Venceras'],
        ['diseño', 'Ventajas de un buen diseño'],
        ['crc', 'Tarjetas Clase-Responsabilidad-Colaborador'],
        // arquitecturas
        ['definicion', '¿ Que es una arquitectura ?'],
        ['capas', 'Capas'],
        ['cliente', 'Cliente-Servidor'],
        ['intermediario', 'Intermediario'],
        ['servicios', 'MicroServicios'],
        ['hexagonal', 'Hexagonal'],
        ['otrasArquitecturas', 'Otras Arquitecturas'],
        // buenas practicas
        ['practicas1', 'Buenas practicas parte #1'],
        ['practicas2', 'Buenas practicas parte #2'],
        ['practicas3', 'Buenas practicas parte #3'],
        ['practicas4', 'Buenas practicas parte #4'],
        ['demeter', 'Ley de Demeter'],
        ['complejidad', 'Complejidad Ciclomatica'],
        ['logging', 'Logging VS Debugging'],
        // calidad
        ['metricas', 'Metricas del Software'],
        ['metricasEnCodigo', 'Metricas del codigo'],
        ['cleanCode', 'Clean Code & Code rot'],
        // compilación
        ['compilacion', '¿ Que es compilar ?'],
        ['nivel', 'Niveles de compilación'],
        ['interprete', 'Tipos de lenguajes'],
        ['transpilacion', '¿ Que es la transpilación ?'],
        // conocimientos empiricos
        ['balas', 'Balas de Plata'],
        ['lehman', 'Leyes de Lehman'],
        ['conway', 'Ley de Conway'],
        ['murphy', 'Ley de Murphy'],
        ['cristales', 'Efecto de los cristales rotos'],
        ['quo', 'Status Quo'],
        ['costo', 'Falacia del costo hundido'],
        ['tiposProgramadores', 'Tipos de programadores'],
        ['sesgos', 'Algunos Sesgos cognitivos'],
        ['multitarea', 'Pros y Contras del multitasking'],
        ['maxwellCurve', 'La curva de Maxwell'],
        ['pendulo', 'Ley del pendulo'],
        // docker
        ['docker', '¿ Que es Docker ?'],
        ['images', '¿ Que es una imagen ?'],
        ['containers', '¿ Que es un contenedor ?'],
        ['volumes', '¿ Que es un volumen ?'],
        ['network', 'Manejo de redes en Docker'],
        ['file', 'Comandos que acepta Docker'],
        ['compose', 'Manejo del docker-compose'],
        // estrategias de desarrollo
        ['ddd', 'Diseño Orientado a Dominios'],
        ['bdd', 'Desarrollo Dirigido por Comportamiento'],
        ['tdd', 'Desarrollo Dirigido por Tests'],
        ['atdd', 'Desarrollo guiado por pruebas de aceptación'],
        ['analisis', 'Bottom Up & Top Down'],
        ['tld', 'Tests al final del desarrollo'],
        // frameworks
        ['frameworks', '¿ Que es un framework?'],
        ['ioc', 'Inversion de Control'],
        ['iod', 'Inyección de dependencias'],
        ['spring', 'Spring Framework'],
        ['angular', 'Angular Framework'],
        // git
        ['introduccion', 'Introducción a Git'],
        ['repositorios', 'Repositorios Remotos y Locales'],
        ['ramas', 'Manejo de ramas'],
        ['protocolos', 'Comunicación entre repositorios'],
        ['versiones', 'Versiones mediante etiquetas'],
        ['forks', 'Solicitudes a otros proyectos'],
        ['stash', 'Estados de trabajo'],
        ['merge', 'Union de ramas'],
        ['atributos', 'Personalización y cambio de acciones por defecto'],
        ['migracion', 'Migración de otros sistemas y otras acciones'],
        ['flow', 'Flujo de trabajo con Git'],
        ['remotos', 'Repositorios Remotos'],
        ['practicas', 'Buenas practicas para realizar commits'],
        // historias de usuario
        ['historias', '¿ Que son las HU ?'],
        ['objetivos', '¿ Que busca una HU ?'],
        ['partes', 'Partes de una HU'],
        ['invest', 'Criterio INVEST'],
        ['smart', 'Criterio SMART'],
        ['3c', 'Card-Conversación-Confirmación'],
        ['gherkin', 'Definición de los criterios de aceptación'],
        ['descomposicionHU', 'Descomposición en tareas'],
        ['agil', 'Manifiesto Agil'],
        // malas practicas
        ['callbackhell', 'Cadena de llamados asincronos'],
        ['cosas1', 'Malas practicas parte #1'],
        ['cosas2', 'Malas practicas parte #2'],
        ['cosas3', 'Malas practicas parte #3'],
        // meta-caracteristicas
        ['metaDatos', ' ¿ Que son los metadatos ?'],
        ['metaClase', '¿ Que es una meta clase ?'],
        ['reflexion', 'Auto mutabilidad del codigo'],
        ['asserts', 'Comprobaciones del codigo'],
        ['excepciones', 'Lanzamiento y manejo de excepciones'],
        ['scafolding', 'Creación automatica de codigo'],
        ['cache', 'Cache y sus estrategias'],
        // metodologias
        ['agiles', '¿ Que son las metodologias agiles ?'],
        ['scrum', 'Scrum'],
        ['kanban', 'Kanban'],
        ['elevator', 'Elevator Pitch'],
        ['canvas', 'Canvas'],
        ['tradicionales', 'Metodologias Tradicionales'],
        ['cascada', 'Cascada'],
        ['espiral', 'Espiral'],
        ['iterativo', 'Iterativo-incremental'],
        ['extrema', 'Programación Extrema'],
        ['v', 'Modelo en V'],
        ['rup', 'Proceso Racional Unificado'],
        ['kaizen', 'Kaizen'],
        // nube
        ['nube', 'Tipos de nube'],
        ['iaas-paas-saas', 'IaaS, PaaS, SaaS'],
        ['api', 'API'],
        ['rest', 'SOAP vs REST'],
        ['restfull', 'Rest & Restfull'],
        ['caracteristicas', 'Caracteristicas de una api restfull'],
        ['madurezDeUnaApi', 'Nivel de madurez de una API'],
        // otros
        ['escalamiento', 'Escalamiento de un sistema'],
        ['scraping', 'Web Scrapping'],
        ['cdci', 'Integración continua y Entrega Continua'],
        ['devops', 'DevOps'],
        ['scope', 'Alcance'],
        ['precedencia', 'Precedencia y jerarquia de operaciones'],
        ['mvp', 'Minimo Producto Viable'],
        ['artesanos', 'Artesanos de software'],
        ['verticalAndHorizontal', 'Organización de un proyecto'],
        // paradigmas
        ['imperativo', 'Paradigmas Imperativo & Declarativo'],
        ['funcional', 'Paradigma funcional'],
        ['scripting', 'Lenguajes de scripting'],
        ['reactiva', 'Programación reactiva'],
        ['marcado', 'Lenguajes de marcado'],
        ['aspectos', 'Orientación a aspectos'],
        // patrones
        ['definicionPatrones', '¿ Que son los patrones ? '],
        ['gof', 'Gang of Four (GoF)'],
        ['desglosegof', 'Definciones de cada tipo'],
        ['grasp', 'Patrones de software de asignación de responsabilidades'],
        ['desglosegrasp', 'Patrones GRASP'],
        ['dao', 'Data Acess Object'],
        ['antipatrones', 'Antipatrones más importantes'],
        // personas
        ['personasYprocesos', 'Personas-Procesos-Tecnologias'],
        ['gestionDeServicios', 'Gestión de servicios tecnologicos'],
        ['gestionDeActivos', 'Gestión de activos'],
        ['fidelizacion', 'Fidelización de los clientes'],
        // poo
        ['poo', 'Programación Orientada a Objetos'],
        ['pooPilares', 'Pilares de POO'],
        ['composicion', 'Agregación & Composición'],
        ['pooStatic', 'palabra reservada static'],
        ['sobrecarga', 'Sobre carga de metodos'],
        ['acoplamiento', 'Tipos de acoplamiento'],
        ['contratos', 'Diseño por contratos'],
        ['descomposicion', 'Descomposición'],
        ['herencia', 'Herencia'],
        ['polimorfismo', 'Polimorfismo'],
        ['herVScomp', 'Herencia vs Composición'],
        ['enlaces', 'Enlace estatico & dinamico'],
        // pruebas
        ['principios', 'Principios de testing'],
        ['manifiesto', 'Manifiesto para testing '],
        ['tiposPruebas', 'Tipos de pruebas'],
        ['beneficios', 'Beneficios de hacer testing continuamente'],
        ['nombramiento', 'Nombramiento de los componentes'],
        ['first', 'Principio FIRST'],
        ['sutydoc', 'SUT & DOC'],
        ['dobles', 'Dobles'],
        ['aaa', 'Arrange-Act-Assert'],
        ['gwt', 'Given-When-Then'],
        ['piramide', 'Piramide de tests'],
        ['triangulo', 'Triangulo de Hierro'],
        ['cobertura', 'Cobertura de pruebas'],
        ['falsos', 'Falsos positivos & Falsos negativos'],
        ['QAperson', ' ¿ Que es QA ?'],
        // refactorización
        ['codigolimpio', '¿ Que es codigo Limpio ?'],
        ['deudatecnica', 'Deuda tecnica'],
        ['tiposDeudaTecnica', 'Tipos de deuda tecnica'],
        ['comentarios', 'Comentarios especiales'],
        ['cuandorefactorizar', '¿ Cuando refactorizar ?'],
        ['comorefactorizar', '¿ Como refactorizar ? '],
        // requisitos
        ['funcionales', 'Requisitos funcionales'],
        ['NOfuncionales', 'Requisitos No funcionales'],
        ['negocio', 'El valor del negocio'],
        ['ambiguedad', 'Evitar la ambiguedad'],
        ['calidad', 'Atributos de calidad'],
        ['tradeoff', 'Sacrificios y ganancias'],
        // principios
        ['solid', 'Principio SOLID'],
        ['kiss', 'Mantenlo simple, estupido'],
        ['yagni', 'No vas a necesitarlo'],
        ['occam', 'La navaja de Occam'],
        ['dry', 'No te repitas a ti mismo'],
        ['hollywood', 'No nos llames, nosotros te llamamos'],
        ['tellDontAsk', 'Dile, no le preguntes'],
        // seguridad
        ['firewall', 'Firewall'],
        ['protocolos', 'SSL, TSL, HTTPS'],
        ['proxy', 'Proxy'],
        ['estatico', 'Analisis de codigo estatico'],
        ['ciberSeguridad', 'Ciberseguridad y otras amenazas'],
        ['cia', 'Confidencialidad-Integridad-Accesibilidad '],
        ['noRepudio', 'No repudio'],
        ['matrizDeRiesgo', 'Matriz de Riesgo'],
        ['condicionDeCarrera', 'Condición de Carrera'],
        // smells codes
        ['codesmells', 'Smell Codes'],
        ['tiposSmellCodes', 'Tipos de Smell codes'],
        ['desglose', 'Smell codes por tipo'],
        ['casos', 'Casos donde pueden ser ignorados'],
        ['payoff', 'Beneficios de corregir code smells'],
        // sql & No sql
        ['sql', '¿ Que es SQL ? '],
        ['dbms', 'Software de Gestion de Bases de Datos'],
        ['crud', 'Create, Read, Update, Delete'],
        ['dl', 'DDL, DML, DCL, TCL'],
        ['integridad', 'Integridad Referencial'],
        ['erd', 'Diagrama Entidad-Relación'],
        ['normalizacion', 'Normalización de una BD'],
        ['nosql', 'Bases de Datos NO SQL'],
        ['tiposBD', 'Tipos de BD No SQL'],
        ['acid', 'Esquema ACID'],
        ['orm', 'Mapeo Objetos-Relacional'],
        ['consistenciaEventual', 'Consistencia Eventual'],
        // uml
        ['uml', 'Lenguaje Unificado de Modelado'],
        ['clase', 'Diagrama de clases'],
        ['componentes', 'Diagrama de componentes'],
        ['despliegue', 'Diagrama de despliegue'],
        ['usos', 'Diagrama de casos de uso'],
        ['secuencia', 'Diagrama de secuencia'],
        ['actividades', 'Diagrama de actividades'],
        ['paquetes', 'Diagrama de paquetes'],
        ['estados', 'Diagrama de estados'],
        ['vista', 'Modelo 4+1 vistas'],
        // versionamiento
        ['git', 'Gestores de versiones'],
        ['dependencias', 'Gestores de dependencias'],
        ['gradlevsmaven', 'Gradle vs Maven'],
        ['versiones', 'Manejo de versiones'],
        // web
        ['spa', 'Single Page Aplication'],
        ['pwa', 'Progressive Web App'],
        ['seo', 'Search Engine Optimization'],
        ['espacio', 'El uso del espacio para diseñar'],
        ['diseno', 'Diseño grafico']
    ]);

    public getLinkAndTittleByKey(key: string = ''): void {
        this.selection = key;
        this.referencia = this.links.get(key)?.toString() || '';
        this.titulo = this.tittles.get(key)?.toString() || '';
    }

}
