
name: Deploy on Firebase

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        npm install --save --legacy-peer-deps
        npm install -g @angular/cli
        ng build --configuration production --buildOptimizer=true
    - name: Firebase Deploy
      run: |
        sudo npm install -g firebase-tools
        firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}

#https://dev.to/gautemeekolsen/getting-started-with-github-actions-ci-cd-firebase-deploy-5g87
#https://javascript.plainenglish.io/how-to-optimize-your-angular-application-for-production-e80537f1c9e
